-- Enable the pgvector extension to work with embedding vectors
create extension if not exists vector;

-- Create the items table
create table items (
  id uuid primary key default gen_random_uuid(),
  type text check (type in ('lost', 'found')) not null,
  description text,
  generated_description text, -- description generated by AI
  image_url text,
  contact_email text,
  embedding vector(768), -- Gemini embedding dimension (text-embedding-004)
  is_resolved boolean default false,
  created_at timestamptz default now()
);

-- Create a search index for faster vector similarity search
create index on items using hnsw (embedding vector_cosine_ops);

-- Enable Row Level Security (RLS)
alter table items enable row level security;

-- Create a policy that allows anyone to insert items (for the hackathon demo)
create policy "Anyone can insert items"
on items for insert
with check (true);

-- Create a policy that allows anyone to read active items
create policy "Anyone can read items"
on items for select
using (true);

-- Create a storage bucket for images
insert into storage.buckets (id, name, public) 
values ('items', 'items', true);

-- Allow public access to the storage bucket
create policy "Public Access"
on storage.objects for select
using ( bucket_id = 'items' );

create policy "Public Upload"
on storage.objects for insert
with check ( bucket_id = 'items' );
